global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # System metrics via node-exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Django app metrics
  - job_name: 'djangoapi'
    static_configs:
      - targets: ['djangoapi:8000']  # Django's container:port
    metrics_path: '/api/metrics'
